server:
  port: 50301
  servlet:
    context-path: /tower_ningxia

spring:
  #设置上传大小
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB


  #模板引擎
  thymeleaf:
    mode: HTML
    cache: false
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages

  datasource:

#    url: jdbc:mysql://192.168.1.83:3306/tower_ningxia?useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    username: tower_ningxia
#    password: 17e3f8eb574844debd43c59edd7bc18a

    url: jdbc:mysql://localhost:3306/tower?useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: lijian
    password: 12138

    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#览易服务器正式地址
baseUrl: https://wxgame.jicf.net/tower_ningxia/
#本机开发地址
#baseUrl: http://localhost:50100/tower/

#h5Url: http://game.flyh5.cn/resources/game/lzq_game/2019/1021GT/main.html
#praiseH5Url: https://wxsq.tianhongjijin.com.cn/jlyh5/fort/main.html
# prod
#authUrl: http://game.flyh5.cn/game/wxf1e725c242109837/java_authorization/index.php
# test
#authUrl: http://game.flyh5.cn/game/wxf1e725c242109837/java_authorization/index.php

#上传地址
tmpDownload: /data/nas/java/tower_ningxia
main:
  allow-bean-definition-overriding: true
logging:
  level:
    com.wangchen: debug

mybatis-plus:
  #实体类所在包
  typeAliasesPackage: com.wangchen.entity
  #mapper.xml所在位置
  mapper-locations: classpath*:/mapper/*.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*